# Generated by Django 5.2 on 2025-05-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('logo', models.ImageField(upload_to='')),
                ('cover_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
