# Generated by Django 5.2 on 2025-05-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='type',
        ),
        migrations.AddField(
            model_name='seller',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='seller_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('agency', 'Real Estate Agency')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='seller',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='sellers/covers/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='sellers/logos/'),
        ),
    ]
