# Generated by Django 5.2 on 2025-05-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
