# Generated by Django 5.2 on 2025-05-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_is_accepted'),
        ('offers', '0002_offer_status'),
    ]

    operations = [
    ]
