# Generated by Django 5.2 on 2025-05-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designidea',
            name='image_url',
        ),
        migrations.AddField(
            model_name='designidea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='design_ideas/'),
        ),
    ]
