# Generated by Django 5.2 on 2025-05-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0002_remove_designidea_image_url_designidea_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designidea',
            name='description',
        ),
        migrations.RemoveField(
            model_name='designidea',
            name='title',
        ),
    ]
