# Generated by Django 4.2.20 on 2025-05-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rooms', models.DecimalField(decimal_places=1, max_digits=4)),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=4)),
                ('bedrooms', models.DecimalField(decimal_places=1, max_digits=4)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('image', models.CharField(max_length=255)),
            ],
        ),
    ]
