# Generated by Django 5.2 on 2025-05-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
