# Generated by Django 5.2 on 2025-05-06 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_propertyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
    ]
