# Generated by Django 5.2 on 2025-05-06 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_remove_property_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='caption',
        ),
    ]
