# Generated by Django 5.2 on 2025-05-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_remove_propertyimage_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
    ]
