# Generated by Django 5.2 on 2025-05-07 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_remove_propertyimage_caption'),
        ('sellers', '0002_remove_seller_type_seller_city_seller_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellers.seller'),
        ),
    ]
