# Generated by Django 5.2 on 2025-05-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_property_additional_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='additional_info',
        ),
    ]
