# Generated by Django 5.2 on 2025-05-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_remove_property_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
    ]
