# Generated by Django 5.2 on 2025-05-07 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_property_additional_info'),
        ('property', '0008_remove_property_additional_info'),
    ]

    operations = [
    ]
