# Generated by Django 5.2 on 2025-05-08 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_merge_20250507_2041'),
        ('property', '0009_property_additional_info'),
    ]

    operations = [
    ]
