# Generated by Django 5.2 on 2025-05-08 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_merge_20250507_2041'),
        ('sellers', '0002_remove_seller_type_seller_city_seller_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='sellers.seller'),
        ),
    ]
