# Generated by Django 5.2 on 2025-05-08 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_alter_property_seller'),
        ('property', '0010_merge_20250508_1151'),
    ]

    operations = [
    ]
