# Generated by Django 5.2 on 2025-05-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_merge_20250508_1458'),
        ('property', '0011_property_favorites'),
    ]

    operations = [
    ]
