# Generated by Django 5.2 on 2025-05-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_merge_20250508_1505'),
        ('property', '0013_property_is_sold'),
    ]

    operations = [
    ]
