# Generated by Django 5.2 on 2025-05-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_merge_0012_merge_20250508_1505_0013_property_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='open_house_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
