# Generated by Django 5.2.1 on 2025-05-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_property_latitude_property_longitude'),
        ('property', '0015_property_open_house_time'),
    ]

    operations = [
    ]
