# Generated by Django 5.2.1 on 2025-05-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_merge_20250512_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image_url',
            field=models.ImageField(upload_to='property_images/'),
        ),
    ]
