# Generated by Django 5.2 on 2025-05-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_alter_propertyimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
